
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 18 21:23:01 ART 2017
//----------------------------------------------------

package ar.edu.unrc.asp.cfgbuilder.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int THENSYM = 17;
  public static final int TIMES = 4;
  public static final int IFSYM = 15;
  public static final int EQL = 11;
  public static final int PLUS = 2;
  public static final int INT = 20;
  public static final int RBRACE = 9;
  public static final int RPAREN = 7;
  public static final int SLASH = 5;
  public static final int DOSYM = 14;
  public static final int LPAREN = 6;
  public static final int LBRACE = 8;
  public static final int ID = 19;
  public static final int GRT = 13;
  public static final int LSS = 12;
  public static final int EOF = 0;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ELSESYM = 16;
  public static final int WHILESYM = 18;
  public static final int BECOMES = 10;
}

